"""empty message

Revision ID: 500a0ae7f83d
Revises: 
Create Date: 2021-07-05 08:09:37.696721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500a0ae7f83d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test__board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test__board')
    # ### end Alembic commands ###
